version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: courier_postgres
    restart: always
    environment:
      POSTGRES_DB: courierdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: courier_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/courierdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    command: ["java", "-jar", "/app.jar"]

volumes:
  postgres_data: